# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    # We'll use the single-file case for these runs
    NF_BEFORE_SCRIPT: mkdir -p ${CI_PROJECT_NAME}/data/ && wget -O ${CI_PROJECT_NAME}/data/wf-trio-test.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-trio/wf-trio-test.tar.gz && tar -xzvf ${CI_PROJECT_NAME}/data/wf-trio-test.tar.gz -C  ${CI_PROJECT_NAME}/data/
    NF_WORKFLOW_OPTS: "--proband_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg002/hg002.bam \
        --mat_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg004 \
        --pat_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg003 \
        --ref wf-trio/data/wf-trio-test/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta \
        --bed  wf-trio/data/wf-trio-test/Ashkenazi_test_TP.bed"
    CI_FLAVOUR: "new"
    PYTEST_CONTAINER_NAME: "wf-common"
    PYTEST_CONTAINER_CONFIG_KEY: "common_sha="
    RELEASE_WORKFLOW: "no" # do not release this workflow


# Remove this block in downstream templates
singularity-run:
    tags: [] # no need for big ram
# end


docker-run:

    # Remove this directive in downstream templates
    tags: [] # no need for big ram
    parallel:
        matrix:
            - MATRIX_NAME: [ "trio"]
    rules:
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "trio"
          variables:
              NF_BEFORE_SCRIPT: mkdir -p ${CI_PROJECT_NAME}/data/ && wget -O ${CI_PROJECT_NAME}/data/wf-trio-test.tar.gz https://ont-exd-int-s3-euwst1-epi2me-labs.s3.amazonaws.com/wf-trio/wf-trio-test.tar.gz && tar -xzvf ${CI_PROJECT_NAME}/data/wf-trio-test.tar.gz -C ${CI_PROJECT_NAME}/data/
              NF_WORKFLOW_OPTS: "-executor.\\$$local.memory 16GB \
              --proband_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg002/hg002.bam \
              --pat_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg003 \
              --mat_bam wf-trio/data/wf-trio-test/Ashkenazi_test_TP_data/nf_bam_test_hg004 \
              --ref wf-trio/data/wf-trio-test/GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta \
              --bed  wf-trio/data/wf-trio-test/Ashkenazi_test_TP.bed"
